In [3]:
import pandas as pd
import numpy as np
from datetime import time
df = pd.read_excel('Encoders_Clean_01.xlsx')
df.head()

date scanner    min    max   err  errf   minf   maxf  pixels  \
0 2017-12-17    K219  35435  35933  1.40  0.02  35681  35688       6   
1 2017-12-18    H161  35155  36382  3.43  0.08  35731  35761      14   
2 2017-12-18    K211  35305  36042  2.07  0.13  35692  35739      43   
3 2017-12-18    K212  35216  36225  2.82  0.11  35686  35726      61   
4 2017-12-18    K220  35196  36259  2.98  0.04  35709  35724      11   

               updated_at  failure_rate  
0 2017-12-29 16:26:16.475      1.428571  
1 2017-12-29 16:26:16.873      2.332362  
2 2017-12-19 18:10:57.454      6.280193  
3 2017-12-19 18:10:57.460      3.900709  
4 2017-12-19 18:10:57.464      1.342282

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   date          2602 non-null   datetime64[ns]
 1   scanner       2602 non-null   object        
 2   min           2602 non-null   int64         
 3   max           2602 non-null   int64         
 4   err           2602 non-null   float64       
 5   errf          2602 non-null   float64       
 6   minf          2602 non-null   int64         
 7   maxf          2602 non-null   int64         
 8   pixels        2602 non-null   int64         
 9   updated_at    1809 non-null   datetime64[ns]
 10  failure_rate  2602 non-null   float64       
dtypes: datetime64[ns](2), float64(3), int64(5), object(1)
memory usage: 223.7+ KB


In [5]:
df['sca_cat'] = df['scanner'].str[0] # captures the first letter
df['sca_num'] = df['scanner'].str.extract('(\d+)') # captures numerical part
df.head()

date scanner    min    max   err  errf   minf   maxf  pixels  \
0 2017-12-17    K219  35435  35933  1.40  0.02  35681  35688       6   
1 2017-12-18    H161  35155  36382  3.43  0.08  35731  35761      14   
2 2017-12-18    K211  35305  36042  2.07  0.13  35692  35739      43   
3 2017-12-18    K212  35216  36225  2.82  0.11  35686  35726      61   
4 2017-12-18    K220  35196  36259  2.98  0.04  35709  35724      11   

               updated_at  failure_rate sca_cat sca_num  
0 2017-12-29 16:26:16.475      1.428571       K     219  
1 2017-12-29 16:26:16.873      2.332362       H     161  
2 2017-12-19 18:10:57.454      6.280193       K     211  
3 2017-12-19 18:10:57.460      3.900709       K     212  
4 2017-12-19 18:10:57.464      1.342282       K     220

In [6]:
df['sca_cat'].unique()

array(['K', 'H'], dtype=object)

In [7]:
df['sca_cat'].replace({'K':0,'H':1},inplace=True)

In [8]:
df.head()

date scanner    min    max   err  errf   minf   maxf  pixels  \
0 2017-12-17    K219  35435  35933  1.40  0.02  35681  35688       6   
1 2017-12-18    H161  35155  36382  3.43  0.08  35731  35761      14   
2 2017-12-18    K211  35305  36042  2.07  0.13  35692  35739      43   
3 2017-12-18    K212  35216  36225  2.82  0.11  35686  35726      61   
4 2017-12-18    K220  35196  36259  2.98  0.04  35709  35724      11   

               updated_at  failure_rate  sca_cat sca_num  
0 2017-12-29 16:26:16.475      1.428571        0     219  
1 2017-12-29 16:26:16.873      2.332362        1     161  
2 2017-12-19 18:10:57.454      6.280193        0     211  
3 2017-12-19 18:10:57.460      3.900709        0     212  
4 2017-12-19 18:10:57.464      1.342282        0     220

In [9]:
#df['time'] = df['updated_at'].dt.time

#df.head()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   date          2602 non-null   datetime64[ns]
 1   scanner       2602 non-null   object        
 2   min           2602 non-null   int64         
 3   max           2602 non-null   int64         
 4   err           2602 non-null   float64       
 5   errf          2602 non-null   float64       
 6   minf          2602 non-null   int64         
 7   maxf          2602 non-null   int64         
 8   pixels        2602 non-null   int64         
 9   updated_at    1809 non-null   datetime64[ns]
 10  failure_rate  2602 non-null   float64       
 11  sca_cat       2602 non-null   int64         
 12  sca_num       2602 non-null   object        
dtypes: datetime64[ns](2), float64(3), int64(6), object(2)
memory usage: 264.4+ KB


In [11]:
df.drop('scanner', axis=1, inplace=True)

In [12]:
df.head()

date    min    max   err  errf   minf   maxf  pixels  \
0 2017-12-17  35435  35933  1.40  0.02  35681  35688       6   
1 2017-12-18  35155  36382  3.43  0.08  35731  35761      14   
2 2017-12-18  35305  36042  2.07  0.13  35692  35739      43   
3 2017-12-18  35216  36225  2.82  0.11  35686  35726      61   
4 2017-12-18  35196  36259  2.98  0.04  35709  35724      11   

               updated_at  failure_rate  sca_cat sca_num  
0 2017-12-29 16:26:16.475      1.428571        0     219  
1 2017-12-29 16:26:16.873      2.332362        1     161  
2 2017-12-19 18:10:57.454      6.280193        0     211  
3 2017-12-19 18:10:57.460      3.900709        0     212  
4 2017-12-19 18:10:57.464      1.342282        0     220

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   date          2602 non-null   datetime64[ns]
 1   min           2602 non-null   int64         
 2   max           2602 non-null   int64         
 3   err           2602 non-null   float64       
 4   errf          2602 non-null   float64       
 5   minf          2602 non-null   int64         
 6   maxf          2602 non-null   int64         
 7   pixels        2602 non-null   int64         
 8   updated_at    1809 non-null   datetime64[ns]
 9   failure_rate  2602 non-null   float64       
 10  sca_cat       2602 non-null   int64         
 11  sca_num       2602 non-null   object        
dtypes: datetime64[ns](2), float64(3), int64(6), object(1)
memory usage: 244.1+ KB


In [14]:
df['sca_num'].unique()

array(['219', '161', '211', '212', '220', '221', '169', '162', '238',
       '250', '237', '173', '175', '177', '176', '174', '128', '163',
       '239', '141', '148', '131', '132', '134', '133', '135', '138',
       '139', '149', '115', '129', '130', '127', '167', '150', '210',
       '209', '120', '121', '168', '114', '171', '147', '172', '208',
       '218', '170', '112', '113', '143', '142', '151', '152', '154',
       '155', '156', '157', '153', '166', '165'], dtype=object)

In [15]:
df['sca_num'] = df['sca_num'].astype(int)


In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   date          2602 non-null   datetime64[ns]
 1   min           2602 non-null   int64         
 2   max           2602 non-null   int64         
 3   err           2602 non-null   float64       
 4   errf          2602 non-null   float64       
 5   minf          2602 non-null   int64         
 6   maxf          2602 non-null   int64         
 7   pixels        2602 non-null   int64         
 8   updated_at    1809 non-null   datetime64[ns]
 9   failure_rate  2602 non-null   float64       
 10  sca_cat       2602 non-null   int64         
 11  sca_num       2602 non-null   int32         
dtypes: datetime64[ns](2), float64(3), int32(1), int64(6)
memory usage: 233.9 KB


In [17]:
df['date_year'] = df['date'].dt.year
df['date_month'] = df['date'].dt.month
df['date_day'] = df['date'].dt.day


In [18]:
df.head()

date    min    max   err  errf   minf   maxf  pixels  \
0 2017-12-17  35435  35933  1.40  0.02  35681  35688       6   
1 2017-12-18  35155  36382  3.43  0.08  35731  35761      14   
2 2017-12-18  35305  36042  2.07  0.13  35692  35739      43   
3 2017-12-18  35216  36225  2.82  0.11  35686  35726      61   
4 2017-12-18  35196  36259  2.98  0.04  35709  35724      11   

               updated_at  failure_rate  sca_cat  sca_num  date_year  \
0 2017-12-29 16:26:16.475      1.428571        0      219       2017   
1 2017-12-29 16:26:16.873      2.332362        1      161       2017   
2 2017-12-19 18:10:57.454      6.280193        0      211       2017   
3 2017-12-19 18:10:57.460      3.900709        0      212       2017   
4 2017-12-19 18:10:57.464      1.342282        0      220       2017   

   date_month  date_day  
0          12        17  
1          12        18  
2          12        18  
3          12        18  
4          12        18

In [19]:
df.drop('date',axis=1,inplace=True)

In [20]:
df.head()

min    max   err  errf   minf   maxf  pixels              updated_at  \
0  35435  35933  1.40  0.02  35681  35688       6 2017-12-29 16:26:16.475   
1  35155  36382  3.43  0.08  35731  35761      14 2017-12-29 16:26:16.873   
2  35305  36042  2.07  0.13  35692  35739      43 2017-12-19 18:10:57.454   
3  35216  36225  2.82  0.11  35686  35726      61 2017-12-19 18:10:57.460   
4  35196  36259  2.98  0.04  35709  35724      11 2017-12-19 18:10:57.464   

   failure_rate  sca_cat  sca_num  date_year  date_month  date_day  
0      1.428571        0      219       2017          12        17  
1      2.332362        1      161       2017          12        18  
2      6.280193        0      211       2017          12        18  
3      3.900709        0      212       2017          12        18  
4      1.342282        0      220       2017          12        18

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   min           2602 non-null   int64         
 1   max           2602 non-null   int64         
 2   err           2602 non-null   float64       
 3   errf          2602 non-null   float64       
 4   minf          2602 non-null   int64         
 5   maxf          2602 non-null   int64         
 6   pixels        2602 non-null   int64         
 7   updated_at    1809 non-null   datetime64[ns]
 8   failure_rate  2602 non-null   float64       
 9   sca_cat       2602 non-null   int64         
 10  sca_num       2602 non-null   int32         
 11  date_year     2602 non-null   int64         
 12  date_month    2602 non-null   int64         
 13  date_day      2602 non-null   int64         
dtypes: datetime64[ns](1), float64(3), int32(1), int64(9)
memory usage: 274.6 KB


In [22]:
df['Updated_year'] = df['updated_at'].dt.year
df['Updated_month'] = df['updated_at'].dt.month
df['Updated_day'] = df['updated_at'].dt.day

In [23]:
df['hour'] = df['updated_at'].dt.hour
df['minu'] = df['updated_at'].dt.minute
df['sec'] = df['updated_at'].dt.second

In [24]:
df.head()

min    max   err  errf   minf   maxf  pixels              updated_at  \
0  35435  35933  1.40  0.02  35681  35688       6 2017-12-29 16:26:16.475   
1  35155  36382  3.43  0.08  35731  35761      14 2017-12-29 16:26:16.873   
2  35305  36042  2.07  0.13  35692  35739      43 2017-12-19 18:10:57.454   
3  35216  36225  2.82  0.11  35686  35726      61 2017-12-19 18:10:57.460   
4  35196  36259  2.98  0.04  35709  35724      11 2017-12-19 18:10:57.464   

   failure_rate  sca_cat  sca_num  date_year  date_month  date_day  \
0      1.428571        0      219       2017          12        17   
1      2.332362        1      161       2017          12        18   
2      6.280193        0      211       2017          12        18   
3      3.900709        0      212       2017          12        18   
4      1.342282        0      220       2017          12        18   

   Updated_year  Updated_month  Updated_day  hour  minu   sec  
0        2017.0           12.0         29.0  16.0  26.0  16.0  
1        2017.0           12.0         29.0  16.0  26.0  16.0  
2        2017.0           12.0         19.0  18.0  10.0  57.0  
3        2017.0           12.0         19.0  18.0  10.0  57.0  
4        2017.0           12.0         19.0  18.0  10.0  57.0

In [25]:
df.drop('updated_at',axis=1,inplace=True)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   min            2602 non-null   int64  
 1   max            2602 non-null   int64  
 2   err            2602 non-null   float64
 3   errf           2602 non-null   float64
 4   minf           2602 non-null   int64  
 5   maxf           2602 non-null   int64  
 6   pixels         2602 non-null   int64  
 7   failure_rate   2602 non-null   float64
 8   sca_cat        2602 non-null   int64  
 9   sca_num        2602 non-null   int32  
 10  date_year      2602 non-null   int64  
 11  date_month     2602 non-null   int64  
 12  date_day       2602 non-null   int64  
 13  Updated_year   1809 non-null   float64
 14  Updated_month  1809 non-null   float64
 15  Updated_day    1809 non-null   float64
 16  hour           1809 non-null   float64
 17  minu           1809 non-null   float64
 18  sec     

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   min            2602 non-null   int64  
 1   max            2602 non-null   int64  
 2   err            2602 non-null   float64
 3   errf           2602 non-null   float64
 4   minf           2602 non-null   int64  
 5   maxf           2602 non-null   int64  
 6   pixels         2602 non-null   int64  
 7   failure_rate   2602 non-null   float64
 8   sca_cat        2602 non-null   int64  
 9   sca_num        2602 non-null   int32  
 10  date_year      2602 non-null   int64  
 11  date_month     2602 non-null   int64  
 12  date_day       2602 non-null   int64  
 13  Updated_year   1809 non-null   float64
 14  Updated_month  1809 non-null   float64
 15  Updated_day    1809 non-null   float64
 16  hour           1809 non-null   float64
 17  minu           1809 non-null   float64
 18  sec     

In [28]:
df['failure_rate'].mean()

2.746506098375678

In [29]:
df['failure_rate'] = df['failure_rate'].fillna(2.783868178245684)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   min            2602 non-null   int64  
 1   max            2602 non-null   int64  
 2   err            2602 non-null   float64
 3   errf           2602 non-null   float64
 4   minf           2602 non-null   int64  
 5   maxf           2602 non-null   int64  
 6   pixels         2602 non-null   int64  
 7   failure_rate   2602 non-null   float64
 8   sca_cat        2602 non-null   int64  
 9   sca_num        2602 non-null   int32  
 10  date_year      2602 non-null   int64  
 11  date_month     2602 non-null   int64  
 12  date_day       2602 non-null   int64  
 13  Updated_year   1809 non-null   float64
 14  Updated_month  1809 non-null   float64
 15  Updated_day    1809 non-null   float64
 16  hour           1809 non-null   float64
 17  minu           1809 non-null   float64
 18  sec     

In [31]:
df['Updated_month'].unique()

array([12., nan,  1.,  2.,  3.])

In [32]:
df['Updated_day'].unique()

array([29., 19., nan,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 30., 31.,  2.,  1.])

In [33]:
df['Updated_year'] = df['Updated_year'].fillna(method='bfill')
df['Updated_month'] = df['Updated_month'].fillna(method='bfill')
df['Updated_day'] = df['Updated_day'].fillna(method='bfill')

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   min            2602 non-null   int64  
 1   max            2602 non-null   int64  
 2   err            2602 non-null   float64
 3   errf           2602 non-null   float64
 4   minf           2602 non-null   int64  
 5   maxf           2602 non-null   int64  
 6   pixels         2602 non-null   int64  
 7   failure_rate   2602 non-null   float64
 8   sca_cat        2602 non-null   int64  
 9   sca_num        2602 non-null   int32  
 10  date_year      2602 non-null   int64  
 11  date_month     2602 non-null   int64  
 12  date_day       2602 non-null   int64  
 13  Updated_year   2602 non-null   float64
 14  Updated_month  2602 non-null   float64
 15  Updated_day    2602 non-null   float64
 16  hour           1809 non-null   float64
 17  minu           1809 non-null   float64
 18  sec     

In [35]:
df['hour'] = df['hour'].fillna(method='bfill')
df['minu'] = df['minu'].fillna(method='bfill')
df['sec'] = df['sec'].fillna(method='bfill')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   min            2602 non-null   int64  
 1   max            2602 non-null   int64  
 2   err            2602 non-null   float64
 3   errf           2602 non-null   float64
 4   minf           2602 non-null   int64  
 5   maxf           2602 non-null   int64  
 6   pixels         2602 non-null   int64  
 7   failure_rate   2602 non-null   float64
 8   sca_cat        2602 non-null   int64  
 9   sca_num        2602 non-null   int32  
 10  date_year      2602 non-null   int64  
 11  date_month     2602 non-null   int64  
 12  date_day       2602 non-null   int64  
 13  Updated_year   2602 non-null   float64
 14  Updated_month  2602 non-null   float64
 15  Updated_day    2602 non-null   float64
 16  hour           2602 non-null   float64
 17  minu           2602 non-null   float64
 18  sec     

In [37]:
df.head()

min    max   err  errf   minf   maxf  pixels  failure_rate  sca_cat  \
0  35435  35933  1.40  0.02  35681  35688       6      1.428571        0   
1  35155  36382  3.43  0.08  35731  35761      14      2.332362        1   
2  35305  36042  2.07  0.13  35692  35739      43      6.280193        0   
3  35216  36225  2.82  0.11  35686  35726      61      3.900709        0   
4  35196  36259  2.98  0.04  35709  35724      11      1.342282        0   

   sca_num  date_year  date_month  date_day  Updated_year  Updated_month  \
0      219       2017          12        17        2017.0           12.0   
1      161       2017          12        18        2017.0           12.0   
2      211       2017          12        18        2017.0           12.0   
3      212       2017          12        18        2017.0           12.0   
4      220       2017          12        18        2017.0           12.0   

   Updated_day  hour  minu   sec  
0         29.0  16.0  26.0  16.0  
1         29.0  16.0  26.0  16.0  
2         19.0  18.0  10.0  57.0  
3         19.0  18.0  10.0  57.0  
4         19.0  18.0  10.0  57.0

In [38]:
X = df.drop('failure_rate', axis=1)
y = df['failure_rate']

In [39]:
X

min    max   err  errf   minf   maxf  pixels  sca_cat  sca_num  \
0     35435  35933  1.40  0.02  35681  35688       6        0      219   
1     35155  36382  3.43  0.08  35731  35761      14        1      161   
2     35305  36042  2.07  0.13  35692  35739      43        0      211   
3     35216  36225  2.82  0.11  35686  35726      61        0      212   
4     35196  36259  2.98  0.04  35709  35724      11        0      220   
...     ...    ...   ...   ...    ...    ...     ...      ...      ...   
2597  35185  35958  2.17  0.07  35541  35565      48        0      168   
2598  35220  36071  2.39  0.06  35715  35735      17        0      114   
2599  35109  35912  2.26  0.08  35504  35531      50        0      171   
2600  35181  36229  2.94  0.04  35702  35715       9        0      220   
2601  35288  36266  2.73  0.01  35734  35737       3        0      221   

      date_year  date_month  date_day  Updated_year  Updated_month  \
0          2017          12        17        2017.0           12.0   
1          2017          12        18        2017.0           12.0   
2          2017          12        18        2017.0           12.0   
3          2017          12        18        2017.0           12.0   
4          2017          12        18        2017.0           12.0   
...         ...         ...       ...           ...            ...   
2597       2018           3         7        2018.0            3.0   
2598       2018           3         7        2018.0            3.0   
2599       2018           3         7        2018.0            3.0   
2600       2018           3         7        2018.0            3.0   
2601       2018           3         7        2018.0            3.0   

      Updated_day  hour  minu   sec  
0            29.0  16.0  26.0  16.0  
1            29.0  16.0  26.0  16.0  
2            19.0  18.0  10.0  57.0  
3            19.0  18.0  10.0  57.0  
4            19.0  18.0  10.0  57.0  
...           ...   ...   ...   ...  
2597          8.0  12.0  24.0  51.0  
2598          8.0  12.0  24.0  51.0  
2599          8.0  12.0  24.0  51.0  
2600          8.0  14.0  42.0  19.0  
2601          8.0  14.0  42.0  19.0  

[2602 rows x 18 columns]

In [40]:
y

0       1.428571
1       2.332362
2       6.280193
3       3.900709
4       1.342282
          ...   
2597    3.225806
2598    2.510460
2599    3.539823
2600    1.360544
2601    0.366300
Name: failure_rate, Length: 2602, dtype: float64

In [41]:
#df['failure_rate'] = df['failure_rate'].astype(int)

In [42]:
df['failure_rate']

0       1.428571
1       2.332362
2       6.280193
3       3.900709
4       1.342282
          ...   
2597    3.225806
2598    2.510460
2599    3.539823
2600    1.360544
2601    0.366300
Name: failure_rate, Length: 2602, dtype: float64

In [43]:
#df['failure_rate'] = np.round(df['failure_rate'],decimals=0)

In [44]:
df['Updated_year'] = df['Updated_year'].astype(int)
df['Updated_month'] = df['Updated_month'].astype(int)
df['Updated_day'] = df['Updated_day'].astype(int)

In [45]:
df['hour'] =df['hour'].astype(int)
df['minu'] =df['minu'].astype(int)
df['sec'] = df['sec'].astype(int)

In [46]:
#df['err'] = np.round(df['err'],decimals=0)

In [47]:
#df['errf'] = np.round(df['errf'],decimals=0)

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [50]:
print(X_train.shape)
print(X_test.shape)

(2081, 18)
(521, 18)


In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2602 entries, 0 to 2601
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   min            2602 non-null   int64  
 1   max            2602 non-null   int64  
 2   err            2602 non-null   float64
 3   errf           2602 non-null   float64
 4   minf           2602 non-null   int64  
 5   maxf           2602 non-null   int64  
 6   pixels         2602 non-null   int64  
 7   failure_rate   2602 non-null   float64
 8   sca_cat        2602 non-null   int64  
 9   sca_num        2602 non-null   int32  
 10  date_year      2602 non-null   int64  
 11  date_month     2602 non-null   int64  
 12  date_day       2602 non-null   int64  
 13  Updated_year   2602 non-null   int32  
 14  Updated_month  2602 non-null   int32  
 15  Updated_day    2602 non-null   int32  
 16  hour           2602 non-null   int32  
 17  minu           2602 non-null   int32  
 18  sec     

In [52]:
df.head()

min    max   err  errf   minf   maxf  pixels  failure_rate  sca_cat  \
0  35435  35933  1.40  0.02  35681  35688       6      1.428571        0   
1  35155  36382  3.43  0.08  35731  35761      14      2.332362        1   
2  35305  36042  2.07  0.13  35692  35739      43      6.280193        0   
3  35216  36225  2.82  0.11  35686  35726      61      3.900709        0   
4  35196  36259  2.98  0.04  35709  35724      11      1.342282        0   

   sca_num  date_year  date_month  date_day  Updated_year  Updated_month  \
0      219       2017          12        17          2017             12   
1      161       2017          12        18          2017             12   
2      211       2017          12        18          2017             12   
3      212       2017          12        18          2017             12   
4      220       2017          12        18          2017             12   

   Updated_day  hour  minu  sec  
0           29    16    26   16  
1           29    16    26   16  
2           19    18    10   57  
3           19    18    10   57  
4           19    18    10   57

In [53]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [54]:
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [55]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Assuming y_test and y_pred are your actual and predicted values
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")


MAE: 0.58
MSE: 1.20
RMSE: 1.10
R2 Score: 0.87


In [56]:
lr.predict(np.array([35216,36225,2.82,0.11,35686,35726,61,0,212,2017,12,18,2017.0,12.0,19.0,18.0,10.0,57.0]).reshape(1,18))

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.37423177])

In [57]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()

In [58]:
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)

In [59]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")

MAE: 0.09
MSE: 0.25
RMSE: 0.50
R2 Score: 0.97


In [60]:
dt.predict(np.array([35216,36225,2.82,0.11,35686,35726,61,0,212,2017,12,18,2017.0,12.0,19.0,18.0,10.0,57.0]).reshape(1,18))

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([3.90070922])

In [61]:
from sklearn.ensemble import RandomForestRegressor
RFR =  RandomForestRegressor()
RFR.fit(X_train,y_train)
y_pred = RFR.predict(X_test)

In [62]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")

MAE: 0.06
MSE: 0.13
RMSE: 0.36
R2 Score: 0.99


In [63]:
RFR.predict(np.array([35216,36225,2.82,0.11,35686,35726,61,0,212,2017,12,18,2017.0,12.0,19.0,18.0,10.0,57.0]).reshape(1,18))

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([3.94715756])

In [769]:
from sklearn.ensemble import GradientBoostingRegressor
GBR = GradientBoostingRegressor()

In [771]:
GBR.fit(X_train,y_train)
y_pred = GBR.predict(X_test)

In [772]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")

MAE: 0.11
MSE: 0.19
RMSE: 0.43
R2 Score: 0.98


In [782]:
GBR.predict(np.array([35216,36225,2.82,0.11,35686,35726,61,0,212,2017,12,18,2017.0,12.0,19.0,18.0,10.0,57.0]).reshape(1,18))

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(


array([3.97440617])

In [773]:
from sklearn.ensemble import AdaBoostRegressor
ADR = AdaBoostRegressor()

In [774]:
ADR.fit(X_train,y_train)
y_pred = ADR.predict(X_test)

In [775]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")

MAE: 0.70
MSE: 0.79
RMSE: 0.89
R2 Score: 0.91


In [785]:
ADR.predict(np.array([35216,36225,2.82,0.11,35686,35726,61,0,212,2017,12,18,2017.0,12.0,19.0,18.0,10.0,57.0]).reshape(1,18))

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but AdaBoostRegressor was fitted with feature names
  warnings.warn(


array([3.87214638])

MAE stands for Mean Absolute Error. It is a commonly used metric in machine learning to measure the accuracy of a model's predictions.

The MAE is calculated by taking the absolute difference between the predicted values and the true values, and then taking the mean of those absolute differences.

Mathematically, if we have n observations, the MAE can be calculated as:

MAE = (1/n) * Σ|i=1 to n| (yi - ŷi)

where:

yi is the i-th true value
ŷi is the i-th predicted value
|.| represents the absolute value
Σ is the sum over i=1 to n
The MAE is a measure of the average magnitude of the errors in the predictions of a model, without considering their direction. A lower MAE indicates better accuracy of the model.

MSE stands for Mean Squared Error, which is a commonly used metric to evaluate the performance of regression models in machine learning. The MSE measures the average squared difference between the predicted and actual values of a regression problem.

Mathematically, MSE is calculated as the average of the squared differences between the predicted and actual values of the target variable. It is given by the following formula:

MSE = 1/n * ∑(yi - ŷi)²

where yi is the actual value of the target variable for the ith observation, ŷi is the predicted value for the ith observation, and n is the total number of observations.

A lower value of MSE indicates better performance of the regression model, as it indicates that the predicted values are closer to the actual values.

RMSE stands for Root Mean Squared Error, which is a commonly used metric in machine learning to evaluate the performance of regression models. It measures the difference between the predicted values and the actual values of a target variable in a dataset.

RMSE is calculated by taking the square root of the mean of the squared differences between the predicted and actual values. It is expressed in the same units as the target variable, which makes it easy to interpret.

The formula for RMSE is:

RMSE = sqrt(mean((y_pred - y_true)^2))

where y_pred is the predicted value, y_true is the actual value, and mean represents the average of the differences between the predicted and actual values.

The lower the value of RMSE, the better the performance of the regression model.

R2 (R-squared) score is a statistical measure used in machine learning to evaluate the performance of a regression model. It measures how well the model fits the actual data by calculating the proportion of the variance in the dependent variable that is explained by the independent variables.

The R2 score is a value between 0 and 1, where 1 indicates that the model perfectly fits the data, and 0 indicates that the model provides no information about the dependent variable. An R2 score of 0.5 means that 50% of the variance in the dependent variable is explained by the independent variables, while the other 50% is due to random variation.

R2 score is widely used in machine learning to evaluate the performance of regression models, as it provides a simple and interpretable way to assess the goodness of fit. However, it has some limitations, such as being sensitive to outliers and the number of variables used in the model.

In [64]:
import pickle
pickle.dump(RFR,open('pmpmodel.pkl','wb'))